- name: check if plpgsql is already loaded
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ georchestra_dbname }} -t -c "\dx"
  register: loaded_extensions

- name: createlang plpgsql
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ georchestra_dbname }} -t -c "CREATE EXTENSION plpgsql;"
  when: "loaded_extensions.stdout is defined and 'plpgsql' not in loaded_extensions.stdout"

- name: check if postgis is already loaded
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ georchestra_dbname }} -t -c "\dT"
  register: loaded_types

- name: create postgis extension
  sudo: yes
  sudo_user: postgres
  command: psql -d {{ georchestra_dbname }} -t -c "CREATE EXTENSION postgis;"
  when: "loaded_types.stdout is defined and 'geometry' not in loaded_types.stdout"

- name: grant SELECT privilege to georchestra user on spatial_ref_sys table
  sudo: yes
  sudo_user: postgres
  postgresql_privs:
    database: "{{ georchestra_dbname }}"
    privs: SELECT
    type: table
    roles: "{{ georchestra_dbuser }}"
    objs: spatial_ref_sys

- name: grant SELECT|INSERT|DELETE privileges to georchestra user on geometry_columns
  sudo: yes
  sudo_user: postgres
  postgresql_privs:
    database: "{{ georchestra_dbname }}"
    privs: SELECT,INSERT,DELETE
    type: table
    roles: "{{ georchestra_dbuser }}"
    objs: geometry_columns
