- name: installing dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
  - tomcat8
  - tomcat8-user #needed for tomcat8-create-instance

- name: disable default instance
  service: name=tomcat8 state=stopped enabled=no

- name: /etc/tomcat8/keystore already exists ?
  stat: path=/etc/tomcat8/keystore
  register: keystore_stat

- name: create keystore
  command: >
    keytool -genkey -alias localhost
      -keystore /etc/tomcat8/keystore
      -storepass {{ tomcat_keystore_pass }}
      -keypass {{ tomcat_keystore_pass }}
      -keyalg RSA
      -keysize 2048
      -dname "{{ tomcat_keystore_dbname }}"
    creates=/etc/tomcat8/keystore
  when: not keystore_stat.stat.exists

- name: create tomcat_basedir
  file: name={{ tomcat_basedir }} state=directory

- name: create common logdir
  file: path={{ logs_basedir }} state=directory owner=tomcat8 group=tomcat8
