- name: georchestra deployment
  hosts: prod
  sudo: yes
  roles:
    - georchestra
  vars:
    openldap_basedn: dc=georchestra,dc=univ-fcomte,dc=fr
    openldap_rootdn: cn=admin,dc=georchestra,dc=univ-fcomte,dc=fr
    openldap_rootpw: secret
    openldap_commit: 8e606269a23ee8605b1d3b686670d7e173a8debd
    georchestra_fqdn: georchestra-mshe.univ-fcomte.fr
    georchestra_dbname: georchestra
    georchestra_dbuser: www-data
    georchestra_dbpass: www-data
    geonetwork_schema: geonetwork
    geonetwork_dbuser: geonetwork
    geonetwork_dbpass: www-data
    geonetwork_datadir: /var/www/geonetwork/data
    geoserver_privileged_user: geoserver_privileged_user
    geoserver_privileged_pass: gerlsSnFd6SmM
    geoserver_datadir: /var/www/geoserver/data
    geoserver_wms_srslist: [2154, 3857, 3942, 3943, 3944, 3945, 3946, 3947, 3948, 3949, 3950, 4171, 4258, 4326, 23030, 23031, 23032, 32630, 32631, 32632, 4171, 4271, 3758]
    geowebcache_datadir: /var/www/geowebcache/data
    extractor_datadir: /var/www/extractor/data
    mapfishapp_datadir: /var/www/mapfishapp/data
    tomcat_keystore_pass: tomcatkstp
    tomcat_keystore_dbname: CN=georchestra-mshe.univ-fcomte.fr, OU=THEMA, O=CNRS-UFC, L=Besancon, ST=Franche-Comte, C=FR
    tomcat_basedir: /var/lib/tomcat
    logs_basedir: /var/log/orchestra
    ldapadmin_adminemail: thema-info@univ-fcomte.fr
    apache_fullhttps: true
    apache_certpki: true
    apache_certnumber: 29301
    tomcat_instances: {
      proxycas: { port: 8180, control_port: 8105 },
      geoserver: { port: 8280, control_port: 8205 },
      georchestra: { port: 8380, control_port: 8305 }
    }
    georchestra_wars: {
      analytics: { url: analytics, job: georchestra-template-stable, tomcat: georchestra },
      cas: { url: cas-server-webapp, job: georchestra-template-stable, tomcat: proxycas },
      catalogapp: { url: catalogapp, job: georchestra-template-stable, tomcat: georchestra },
      downloadform: { url: downloadform, job: georchestra-template-stable, tomcat: georchestra },
      extractorapp: { url: extractorapp, job: georchestra-template-stable,  tomcat: georchestra },
      geonetwork: { url: geonetwork/web, job: georchestra-template-stable,  tomcat: georchestra },
      geoserver: { url: geoserver/webapp, job: georchestra-template-geofence, tomcat: geoserver },
      geowebcache: { url: geowebcache-webapp, job: georchestra-template-stable, tomcat: georchestra },
      geofence: { url: geoserver/geofence-webapp, job: georchestra-template-geofence, tomcat: georchestra },
      header: { url: header, job: georchestra-template-stable, tomcat: georchestra },
      ldapadmin: { url: ldapadmin, job: georchestra-template-stable, tomcat: georchestra },
      mapfishapp: { url: mapfishapp, job: georchestra-template-stable, tomcat: georchestra },
      ROOT: { url: security-proxy, job: georchestra-template-stable, tomcat: proxycas }
    }
